#!/usr/bin/python

import logging
import time
from influxdb import InfluxDBClient
from pyping import ping

HOSTS = ['8.8.8.8', '216.58.209.78', '213.180.141.140']

logging.basicConfig(level=logging.DEBUG)
influx = InfluxDBClient(database='network')

while True:
    for host in HOSTS:
        try:
            cnt = 1
            r = ping(host, count=cnt)
            rtt = float(r.avg_rtt) if r.avg_rtt else 0.0
            fields = dict(sent=cnt, lost=int(r.packet_lost))
            if r.avg_rtt:
                fields['rtt'] = float(r.avg_rtt)
            p = dict(
                measurement='pings',
                tags=dict(host=host),
                fields=fields,
            )
            logging.debug("p={}".format(p))
            influx.write_points([p])
        except Exception as e:
            logging.error(e, exc_info=True)
    time.sleep(1)
